<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <VersionPrefix>1.0.0</VersionPrefix>
    <Authors>Mudabbirul Saad</Authors>
    <Company>Mudabbirul Saad</Company>
    <Product>NetPulse</Product>
    <RepositoryUrl>https://github.com/MudabbirulSaad/NetPulse</RepositoryUrl>
  </PropertyGroup>
</Project>
